### ISSUE TITLE
vmware/centos nfs-utils missing

### ISSUE THREAD

**Issue by immutef** [misheska/basebox-packer#17]
Prevents from mounting shared folders via NFS with VMWare (Fusion) provider. This may also fail on VirtualBox.

You may want to add the following to the `templates/centos/script/base.sh`:

```
yum install -y nfs-utils
```

**Comment by misheska** [comment]
Looks like it is better to add this to the kickstart than to the postinstall - I see odd issues with CentOS 6.1 & 6.2 in particular - moved
