### ISSUE TITLE
Error on running "packer build -var "provisioner=chef" ubuntu1310.json" within corresponding template folder

### ISSUE THREAD

**Issue by josefglatz** [misheska/basebox-packer#25]
Everytime I want to install chef latest provisioner, it fails.

```
==> Some builds didn't complete successfully and had errors:
--> vmware: Script exited with non-zero exit status: 1
--> virtualbox: Script exited with non-zero exit status: 1
```

**Comment by misheska** [comment]
You also need to provide a version, so the correct command line should be:
packer build -var "provisioner=chef" -var "provisioner_version=latest" ubuntu1310.json

I made a blank string the default so there would be no version in the "provisionerless" build, though I'm open to other suggestions on how to do this.

**Comment by josefglatz** [comment]
Ah ok, sorry. So i will test it later :+1:  Thx & sorry...

**Comment by misheska** [comment]
Not a problem.  It is not clear that they need to be used in a pair (and my documentation on this is way down at the bottom of the README).  The idea is if someone wants to add, say a puppet or some other provisioner that needs a node footprint can add it there (though my only need is for Chef).

I think I will break apart my README into two files, one for the index of downloadable baseboxes and another for the actual README, as that list of baseboxes is really long and most people wouldn’t think that there is actual documentation at the end of that list ;-)

**Comment by josefglatz** [comment]
I would suggest to insert "latest" as default if no version parameter is given.

Am 22.12.2013 um 18:23 schrieb Mischa Taylor notifications@github.com:

> Not a problem. It is not clear that they need to be used in a pair (and my documentation on this is way down at the bottom of the README). The idea is if someone wants to add, say a puppet or some other provisioner that needs a node footprint can add it there (though my only need is for Chef). 
> 
> I think I will break apart my README into two files, one for the index of downloadable baseboxes and another for the actual README, as that list of baseboxes is really long and most people wouldn’t think that there is actual documentation at the end of that list ;-) 
>

**Comment by misheska** [comment]
I agree, but I don’t see a good way to do conditional variables in a Packer template definition.  As far as I can tell, either we can have a “provisionerless” without “latest” OR “provisioner” with “latest”.  That is my conundrum.
