### ISSUE TITLE
misheska-ubuntu1204 "vmware_fusion" box appears to be vmware_desktop

### ISSUE THREAD

**Issue by mkocher** [misheska/basebox-packer#3]
Here's a gist with my Vagrantfile and the output: https://gist.github.com/mkocher/6526747

The virtualbox box works great, but the link for a fusion box seems to lead to the wrong box?

**Comment by misheska** [comment]
Thanks for the feedback Matthew.  It is supposed to be "vmware_desktop".  In theory this should allow a box to work with both the "vmware_fusion" and "vmware_workstation" providers.  This is why Mitchell H made this the default in packer-created baseboxes (with no ability to override this setting).

I think you may need to upgrade your vagrant vmware_fusion provider with the command "vagrant plugin install vmware-vmware-fusion".  I was able to use your Vagrantfile without any issues.  In the past I had trouble running the command "vagrant up --provider=vmware_fusion" against a basebox marked "vmware_desktop", but not recently.

As a last resort you can download the .box file, untar it, edit the "metadata.json" file, change it to be "vmware_fusion" and re-tar it back up again (a ".box" file is just a .tar file), but upgrading the vmware_fusion plugin should address the issue.
