### ISSUE TITLE
Wrong filename (swp)

### ISSUE THREAD

**Issue by hbokh** [misheska/basebox-packer#30]
There is a file named

```
.install-openssh-sshd.bat.swp
```

in "basebox-packer/template/windows2012r2/floppy".
Should be 

```
install-openssh-sshd.bat
```

instead.

**Comment by rasa** [comment]
Fixed in https://github.com/misheska/basebox-packer/commit/d1fb3dad29e19b2a2cc28632e05482f712748fee
