### ISSUE TITLE
Windows 7 template WinRM not working

### ISSUE THREAD

**Issue by misheska** [misheska/basebox-packer#31]
Currently after Sysprep, in the Windows 7 templates, despite having a OOBE Network setting of "Work", WinRM isn't properly enabled because the Network type is set to "Public" and it needs to be either "Work" or "Home".

WinRM refuses to configure if the network adapter type is "Public", and thus doesn't work.

So you'll notice that all the Windows 7 templates don't work because vagrant can't connect to them.  This can be fixed by hand by setting the Network type to "Work", then re-running the winrm config script.

Looking in to a way to fix this in an automated fashion.

I never noticed this issue in the Windows 7 templates because I wasn't trying to use WinRM until recently with the switch to using vagrant-windows.  These Windows 7 templates never worked properly with WinRM.

**Comment by misheska** [comment]
This looks promising:
http://powertoe.wordpress.com/2009/12/28/enable-powershell-remoting-while-running-vmware-workstation-in-a-domain/
http://blogs.msdn.com/b/powershell/archive/2009/04/03/setting-network-location-to-private.aspx
http://www.sevenforums.com/tutorials/43629-network-location-set-home-work-public-network.html

**Comment by misheska** [comment]
Per Ross Smith, in an upcoming PR...

Moved WinRM configuration commands to install-winrm.cmd, to allow easier logging/debugging (Autounattend.xml)
Fixed several WinRM configuration (http://pastie.org/8581033 ) (install-winrm.cmd)
All WinRM configuration commands now run without error (http://pastie.org/8582660 )
Added floppy/set-all-networks-to-private.ps1, which is called by install-winrm.cmd

**Comment by rasa** [comment]
Thanks for posting this. I've already done the work and will post the PR soon!

**Comment by misheska** [comment]
Windows 7 template is now functional for both VirtualBox and VMware
