### ISSUE TITLE
Typo in all Windows templates setting winrm to auto start

### ISSUE THREAD

**Issue by misheska** [misheska/basebox-packer#32]
Everyone's been copying this line from the Veewee templates to configure winrm to auto-start (including me):
  cmd.exe /c sc config winrm start=auto

This is incorrect and the command will error.  It should be this in all the Sysprep templates:
  cmd.exe /c sc config winrm start= auto

(Need to be a space after the =)

**Comment by rasa** [comment]
Yeah, I found that a couple of weeks back. Here it is failing: http://pastie.org/8581033 and here it is working: http://pastie.org/8582660 . I'm sorry I didn't commit my work... just too damn busy.
