### ISSUE TITLE
00-run-all-scripts.cmd in Windows templates enhancements

### ISSUE THREAD

**Issue by misheska** [misheska/basebox-packer#34]
Per Ross Smith,

Skip all .bat/.cmd scripts that start with an underscore (floppy/00-run-all-scripts.cmd)
Added debug variables PACKER_DEBUG and PACKER_PAUSE (floppy/00-run-all-scripts.cmd)
Moved A:\ to end of the PATH, to give precendence to installed applications (floppy/00-run-all-scripts.cmd)
Search for tee.exe in the PATH first, before looking in A:\ (floppy/00-run-all-scripts.cmd)

**Comment by rasa** [comment]
Thanks for posting this. I've already done the work and will post the PR soon!
