### ISSUE TITLE
Use of Powershell in preinstall scripts stymies Windows update slipstreamg

### ISSUE THREAD

**Issue by misheska** [misheska/basebox-packer#35]
Use wget or bitsadmin, if found in the PATH, or on A:\, otherwise use powershell
Skip downloading any file if it's found on a:\, d:\ or in the PATH
This addresses the following issues after slipstreaming Windows updates into installation media:
  After installing all Windows and .Net 3.51 updates, running powershell during installation would produce:
    "Version v4.0.30319 of the .NET Framework is not installed and it is required to run version 3 of Windows PowerShell."
  After installing all Windows and .Net 3.51 updates, and then .NET 4.51 (NDP451-KB2858728-x86-x64-AllOS-ENU.exe),
  running powershell during installation would produce:
    "Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 80070002."

**Comment by rasa** [comment]
Thanks for posting this. I've already done the work and will post the PR soon!

**Comment by rasa** [comment]
After I complete my testing, I will push a new PR soon, that will address this issue.
