### ISSUE TITLE
Problem with VMWare provisioning

### ISSUE THREAD

**Issue by lmayorga1980** [misheska/basebox-packer#43]
For some reason it works on VirtualBox but not on VMWare.

https://github.com/mitchellh/packer/issues/847

Have permissions issues.

**Comment by misheska** [comment]
I think you posted this to the wrong repo.  I think you intended to post this to mitchellh's github - mine seems to provision just fine: https://github.com/misheska/basebox-packer/blob/master/template/ubuntu/ubuntu1204.json
