### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by ncarlson** [misheska/basebox-packer#61]
Hello,

I'd like to fork this repository, but I'm not sure what kind of license the files in this repo fall under.

Would the owner mind adding a LICENSE or COPYING file?

Thanks

**Comment by andreisavu** [comment]
+1

**Comment by dlcarmean** [comment]
+1 also.  A few weeks ago I'd asked the same by direct email but received no reply.

**Comment by rasa** [comment]
Note that all of the box-cutter repos have an Apache 2 license. For example: https://github.com/box-cutter/ubuntu-vm/blob/master/LICENSE

**Comment by keimlink** [comment]
Thanks for the hint @rasa!

**Comment by misheska** [comment]
Actually the license depends on the project, given that box-cutter is a collection of community projects.  Indeed, soon we will be launching the box-cutter organization where the license for the templates will be more clear.  The launch is pending setup of the continuous delivery system around the box source.  The current source does not yet have a complete set of verification builds wired in, so I can't make any guarantees about them working right now & expect the source to evolve there short-term pre-launch.  Once box-cutter launches in a few weeks, this source repository will be deprecated and it will be changed to point to box-cutter

**Comment by ncarlson** [comment]
@rasa Thank you!

@misheska I see. Very cool stuff over on the box-cutter account. Thanks for the update.
